"""Profile catalog: ready-made API profiles (load, search, map to a runtime profile).

Two sources, merged: the catalog bundled in the wheel (always available, so
every command works offline) and a remote index published from the main
branch, so a newly merged profile is visible before the next release. The
remote index is cached for CATALOG_INDEX_TTL seconds and any failure falls
back to the cache, then to the bundled copy.
"""

from __future__ import annotations

import importlib.resources
import json
import os
import re
import time
import tomllib
from pathlib import Path
from typing import Any

import httpx
from rich.table import Table

from openapi_cli4ai import config
from openapi_cli4ai._ui import _verbose as _log
from openapi_cli4ai._ui import console

CATALOG_TIERS = ("verified", "community")
_CATALOG_META_FIELDS = ("name", "description", "maintainer", "source")

# Remote index: generated by `catalog index` and committed to profiles/index.json.
CATALOG_INDEX_URL = "https://raw.githubusercontent.com/dbgorilla/openapi-cli4ai/main/profiles/index.json"
CATALOG_INDEX_TTL = 3600  # seconds
CATALOG_INDEX_VERSION = 1
_CATALOG_INDEX_MAX_BYTES = 1024 * 1024
_CATALOG_INDEX_TIMEOUT = httpx.Timeout(3.0, connect=2.0)  # never make an offline user wait
# Set to any value to skip the remote index entirely (CI, air-gapped, tests).
CATALOG_OFFLINE_ENV = "OAC_CATALOG_OFFLINE"
_SLUG_RE = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?")


def _catalog_root() -> Any:
    """Locate the catalog: bundled in the wheel, else profiles/ in a source checkout."""
    try:
        bundled = importlib.resources.files("openapi_cli4ai") / "_catalog"
        if bundled.is_dir():
            return bundled
    except (ModuleNotFoundError, FileNotFoundError, AttributeError, TypeError):
        pass
    dev = Path(__file__).resolve().parents[2] / "profiles"
    return dev if dev.is_dir() else None


def _load_catalog(remote: bool = True) -> list[dict]:
    """Return every catalog profile as a dict with _tier and _slug attached.

    Bundled entries first, then the remote index merged on top (a remote entry
    replaces a bundled one with the same slug). `remote=False` returns only the
    bundled copy; `catalog validate --all` and `catalog index` use that so they
    describe the files in this checkout, not whatever main currently publishes.
    """
    entries = _load_bundled_catalog()
    if not remote:
        return entries
    remote_entries = _fetch_remote_index()
    if not remote_entries:
        return entries
    merged = {e["_slug"]: e for e in entries}
    for entry in remote_entries:
        merged[entry["_slug"]] = entry
    return list(merged.values())


def _load_bundled_catalog() -> list[dict]:
    """Read the catalog shipped in the wheel (or profiles/ in a source checkout)."""
    root = _catalog_root()
    entries: list[dict] = []
    if root is None:
        return entries
    for tier in CATALOG_TIERS:
        tier_dir = root / tier
        if not tier_dir.is_dir():
            continue
        for item in sorted(tier_dir.iterdir(), key=lambda p: p.name):
            if not item.name.endswith(".toml"):
                continue
            try:
                entry = tomllib.loads(item.read_text(encoding="utf-8"))
            except (OSError, tomllib.TOMLDecodeError):
                continue
            entry["_tier"] = tier
            entry["_slug"] = item.name[: -len(".toml")]
            entries.append(entry)
    return entries


# ── Remote index ──────────────────────────────────────────────────────────────
def build_index(entries: list[dict]) -> dict:
    """Serialisable, deterministic index of catalog entries (no timestamps, sorted)."""
    profiles = []
    for entry in sorted(entries, key=lambda e: (e.get("_tier", ""), e.get("_slug", ""))):
        record = {k: v for k, v in entry.items() if not k.startswith("_")}
        record["tier"] = entry.get("_tier")
        record["slug"] = entry.get("_slug")
        profiles.append(record)
    return {"version": CATALOG_INDEX_VERSION, "profiles": profiles}


def index_json(entries: list[dict]) -> str:
    return json.dumps(build_index(entries), indent=2, sort_keys=True) + "\n"


def _index_to_entries(index: Any) -> list[dict] | None:
    """Turn a parsed index into catalog entries. None if the document is malformed.

    Every entry must pass the offline validator; a bad one is skipped, not fatal,
    so one broken profile on main cannot blank the catalog for everyone.
    """
    # Local import: validator imports this module for _catalog_to_profile.
    from openapi_cli4ai.validator import _validate_catalog_entry

    if not isinstance(index, dict) or index.get("version") != CATALOG_INDEX_VERSION:
        return None
    profiles = index.get("profiles")
    if not isinstance(profiles, list):
        return None
    entries: list[dict] = []
    for record in profiles:
        if not isinstance(record, dict):
            continue
        entry = dict(record)
        tier = entry.pop("tier", None)
        slug = entry.pop("slug", None)
        if tier not in CATALOG_TIERS or not isinstance(slug, str) or not _SLUG_RE.fullmatch(slug):
            continue
        entry["_tier"] = tier
        entry["_slug"] = slug
        errors, _warnings = _validate_catalog_entry(entry, check_spec=False)
        if errors:
            _log(f"catalog index: skipping '{slug}': {errors[0]}")
            continue
        entries.append(entry)
    return entries


def _index_cache_path() -> Path:
    return config.CACHE_DIR / "catalog_index.json"


def _download_index() -> Any:
    """GET the remote index. Raises httpx.HTTPError or ValueError on any problem."""
    with httpx.Client(timeout=_CATALOG_INDEX_TIMEOUT, follow_redirects=False) as client:
        resp = client.get(CATALOG_INDEX_URL)
        resp.raise_for_status()
        if len(resp.content) > _CATALOG_INDEX_MAX_BYTES:
            raise ValueError(f"index exceeds {_CATALOG_INDEX_MAX_BYTES // 1024}KB")
        return resp.json()


def _read_index_cache() -> tuple[float, Any] | None:
    try:
        cached = json.loads(_index_cache_path().read_text(encoding="utf-8"))
        return float(cached["fetched_at"]), cached["index"]
    except (OSError, ValueError, KeyError, TypeError):
        return None


def _fetch_remote_index() -> list[dict] | None:
    """Remote catalog entries, via the TTL cache. None means: use the bundled copy only."""
    if os.environ.get(CATALOG_OFFLINE_ENV):
        return None
    cached = _read_index_cache()
    if cached is not None and time.time() - cached[0] < CATALOG_INDEX_TTL:
        return _index_to_entries(cached[1])
    try:
        index = _download_index()
    except (httpx.HTTPError, ValueError) as exc:
        _log(f"catalog index: fetch failed ({exc}); using {'cached' if cached else 'bundled'} catalog")
        return _index_to_entries(cached[1]) if cached else None
    entries = _index_to_entries(index)
    if entries is None:
        _log("catalog index: malformed document; using bundled catalog")
        return None
    try:
        config.ensure_dirs()
        config._atomic_write(_index_cache_path(), json.dumps({"fetched_at": time.time(), "index": index}))
    except OSError as exc:
        _log(f"catalog index: could not write cache: {exc}")
    return entries


def _catalog_find(name: str) -> dict | None:
    for entry in _load_catalog():
        if name in (entry.get("_slug"), entry.get("name")):
            return entry
    return None


def _catalog_to_profile(entry: dict) -> dict:
    """Map a catalog entry to a runtime profile (drop catalog-only metadata)."""
    profile = {k: v for k, v in entry.items() if k not in _CATALOG_META_FIELDS and not k.startswith("_")}
    profile["verify_ssl"] = True
    return profile


def _auth_env_vars(auth: dict) -> list[str]:
    """Environment variables the user must set for this auth config."""
    keys = {
        "api-key": ("env_var",),
        "bearer": ("token_env_var",),
        "basic": ("username_env_var", "password_env_var"),
    }.get(auth.get("type", "none"), ())
    return [auth[k] for k in keys if auth.get(k)]


def _auth_uses_login(auth: dict) -> bool:
    kind = auth.get("type", "none")
    return kind in ("oidc", "device") or (kind == "bearer" and bool(auth.get("token_endpoint")))


def _auth_summary(auth: dict) -> str:
    kind = auth.get("type", "none")
    if _auth_uses_login(auth):
        return f"{kind} → run 'login'"
    env = _auth_env_vars(auth)
    return f"{kind} → set {', '.join(env)}" if env else kind


def _render_catalog(entries: list[dict], title: str) -> None:
    if not entries:
        console.print("[dim]The catalog is empty.[/dim]")
        return
    table = Table(title=f"{title} ({len(entries)})")
    table.add_column("Name", style="cyan")
    table.add_column("Tier")
    table.add_column("Description", style="green")
    for entry in sorted(entries, key=lambda e: (e.get("_tier", ""), e.get("_slug", ""))):
        tier = entry.get("_tier", "community")
        style = "bold green" if tier == "verified" else "yellow"
        table.add_row(entry.get("_slug", "?"), f"[{style}]{tier}[/{style}]", str(entry.get("description", "")))
    console.print(table)
    console.print("[dim]Install one with: openapi-cli4ai catalog install <name>[/dim]")
